import React, { createContext, useContext, useState, useEffect } from 'react';

const SettingsContext = createContext();

// Language translations for the entire app
export const translations = {
  ar: {
    home: 'الرئيسية',
    products: 'المنتجات',
    settings: 'الإعدادات',
    account: 'حسابي',
    darkMode: 'الوضع المظلم',
    notifications: 'التنبيهات',
    language: 'اللغة',
    viewAll: 'عرض الكل',
    cart: 'السلة',
    searchPlaceholder: 'البحث عن المنتجات...',
    all: 'جميع الفئات',
    electronics: 'الإلكترونيات',
    clothing: 'الملابس',
    books: 'الكتب',
    accessories: 'الإكسسوارات',
    aboutUs: 'من نحن',
    contact: 'اتصل بنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    quickLinks: 'روابط سريعة',
    contactUs: 'اتصل بنا',
    followUs: 'تابعنا',
    allRightsReserved: 'جميع الحقوق محفوظة',
    privacy: 'الخصوصية',
    terms: 'الشروط',
    sitemap: 'خريطة الموقع',
    storeDescription: 'متجرك الشامل لجميع المنتجات التقنية. منتجات عالية الجودة وأسعار تنافسية وخدمة ممتازة.',
    myOrders: 'طلباتي',
    wishlist: 'المفضلة',
    paymentMethods: 'طرق الدفع',
    addresses: 'العناوين',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    welcomeToStore: 'مرحباً بكم في متجر التقنية',
    discoverTech: 'اكتشف أحدث التقنيات والأجهزة',
    shopNow: 'تسوق الآن',
    featuredProducts: 'المنتجات المميزة',
    viewAllProducts: 'عرض جميع المنتجات',
    ourProducts: 'منتجاتنا',
    view: 'عرض',
    addToCart: 'أضف إلى السلة',
    backToProducts: 'العودة إلى المنتجات',
    productNotFound: 'المنتج غير موجود',
    shoppingCart: 'سلة التسوق',
    yourCartIsEmpty: 'سلة التسوق فارغة',
    continueShopping: 'مواصلة التسوق',
    total: 'المجموع',
    selectCategory: 'اختر الفئة',
    allCategories: 'جميع الفئات',
    audio: 'الصوتيات',
    wearables: 'الأجهزة القابلة للارتداء',
    cameras: 'الكاميرات',
    gaming: 'الألعاب',
    search: 'بحث',
    nocmt: 'لا توجد تعليقات بعد - كن أول من يشارك أفكارك!',
    commentSectionTitle: 'التعليقات',
    commentButton:'أضف تعليق',
   
      step1:'مرحبا! هذا هو الرأس حيث يمكنك التنقل.',
      step2:'هنا هي ألواح المنتجات. انقر على واحدة لعرض التفاصيل.',
      step3:'هذا الزر يأخذك إلى سلة التسوق الخاصة بك.',
      step4:'? هل تريد تفعيل الوضع المظلم؟',
      skiper:'تخطي',
      langBox:'مرحبا بك في TechStore   يرجى اختيار اللغة',
      logingoogle:'تسجيل الدخول باستخدام Google',
      loginmsg:'تسجيل الدخول للمتابعة',
      loginundermsg:'الوصول إلى المنتجات المميزة',
      exclusive:'مميز',
      discount:'تخفيض',
      securitymsg:'بياناتك والمعاملات دائما محمية وآمنة.',
      paymentmsg:'نحن نقبل جميع البطاقات الائتمانية الرئيسية وPayPal.',
      supportmsg:'فريق الدعم هنا ليساعدك 24/7.',
      deliverymsg:'نحن نقدم خدمات التسليم السريعة والموثوقة.',
      securityTitle:'محمي',
      paymentTitle:'طريقة الدفع',
      supportTitle:'دعم',
      deliveryTitle:'تسليم',
  },
  en: {
    home: 'Home',
    products: 'Products',
    settings: 'Settings',
    account: 'My Account',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    language: 'Language',
    viewAll: 'View All',
    cart: 'Cart',
    searchPlaceholder: 'Search products...',
    all: 'All Categories',
    electronics: 'Electronics',
    clothing: 'Clothing',
    books: 'Books',
    accessories: 'Accessories',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved',
    privacy: 'Privacy',
    terms: 'Terms',
    sitemap: 'Sitemap',
    storeDescription: 'Your one-stop shop for all things tech. Quality products, competitive prices, and excellent service.',
    myOrders: 'My Orders',
    wishlist: 'Wishlist',
    paymentMethods: 'Payment Methods',
    addresses: 'Addresses',
    logout: 'Logout',
    email: 'Email',
    welcomeToStore: 'Welcome to TechStore',
    discoverTech: 'Discover the latest in technology and gadgets',
    shopNow: 'Shop Now',
    featuredProducts: 'Featured Products',
    viewAllProducts: 'View All Products',
    ourProducts: 'Our Products',
    view: 'View',
    addToCart: 'Add to Cart',
    backToProducts: 'Back to Products',
    productNotFound: 'Product not found',
    shoppingCart: 'Shopping Cart',
    yourCartIsEmpty: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    total: 'Total',
    selectCategory: 'Select Category',
    allCategories: 'All Categories',
    audio: 'Audio',
    wearables: 'Wearables',
    cameras: 'Cameras',
    gaming: 'Gaming',
    search: 'Search',
    nocmt: 'No comments yet—be the first to share your thoughts!',
    commentSectionTitle: 'Comments',
    commentButton:'add a comment',
    step1:'Welcome! This is the header where you can navigate.',
    step2:'Here are the product cards. Click one to view details.',
    step3:'This button takes you to your cart.',
    step4:'? do you want to enable dark mode ',
    skiper:'skip',
    langBox:'Welcome to TechStore   Please select your language',
    logingoogle:'Login with Google',
    loginmsg:'login to continue',
    loginundermsg:'access to exclusive products',
    exclusive:'EXCLUSIVE',
    discount:'DISCOUNT',
    securitymsg:'Your data and transactions are always encrypted and secure.',
    paymentmsg:'We accept all major credit cards and PayPal.',
    supportmsg:'Our support team is here to help you 24/7.',
    deliverymsg:'We offer fast and reliable delivery services.',
    securityTitle:'Secure',
    paymentTitle:'Payment Method',
    supportTitle:'Support',
    deliveryTitle:'Delivery',
   
  },
  de: {
    home: 'Startseite',
    products: 'Produkte',
    settings: 'Einstellungen',
    account: 'Mein Konto',
    darkMode: 'Dunkelmodus',
    notifications: 'Benachrichtigungen',
    language: 'Sprache',
    viewAll: 'Alle anzeigen',
    cart: 'Warenkorb',
    searchPlaceholder: 'Produkte suchen...',
    all: 'Alle Kategorien',
    electronics: 'Elektronik',
    clothing: 'Kleidung',
    books: 'Bücher',
    accessories: 'Zubehör',
    aboutUs: 'Über uns',
    contact: 'Kontakt',
    privacyPolicy: 'Datenschutzerklärung',
    termsOfService: 'Nutzungsbedingungen',
    quickLinks: 'Schnellzugriff',
    contactUs: 'Kontaktiere uns',
    followUs: 'Folge uns',
    allRightsReserved: 'Alle Rechte vorbehalten',
    privacy: 'Datenschutz',
    terms: 'Bedingungen',
    sitemap: 'Sitemap',
    storeDescription: 'Ihr One-Stop-Shop für alle technischen Geräte. Qualitätsprodukte, wettbewerbsfähige Preise und exzellenter Service.',
    myOrders: 'Meine Bestellungen',
    wishlist: 'Wunschliste',
    paymentMethods: 'Zahlungsmethoden',
    addresses: 'Adressen',
    logout: 'Abmelden',
    email: 'E-Mail',
    welcomeToStore: 'Willkommen bei TechStore',
    discoverTech: 'Entdecken Sie die neueste Technologie und Gadgets',
    shopNow: 'Jetzt einkaufen',
    featuredProducts: 'Ausgewählte Produkte',
    viewAllProducts: 'Alle Produkte anzeigen',
    ourProducts: 'Unsere Produkte',
    viewAll: 'Alle anzeigen',
    view: 'Ansehen',
    addToCart: 'In den Warenkorb',
    backToProducts: 'Zurück zu den Produkten',
    productNotFound: 'Produkt nicht gefunden',
    shoppingCart: 'Warenkorb',
    yourCartIsEmpty: 'Ihr Warenkorb ist leer',
    continueShopping: 'Weiter einkaufen',
    total: 'Gesamt',
    selectCategory: 'Kategorie auswählen',
    allCategories: 'Alle Kategorien',
    audio: 'Audio',
    wearables: 'Tragbare Geräte',
    cameras: 'Kameras',
    gaming: 'Spiele',
    search: 'Suchen',
    nocmt: 'Noch keine Kommentare - sei der erste, der deine Gedanken teilt!',
    commentButton:'Kommentar hinzufügen',
    step1:'Willkommen! Dies ist der Header, wo Sie navigieren können.',
    step2:'Hier sind die Produktkarten. Klicken Sie auf eines, um Details zu sehen.',
    step3:'Dieser Button führt Sie zu Ihrem Warenkorb.',
    step4:'? möchten Sie den Dunkelmodus aktivieren?',
    skiper:'überspringen',
    langBox:'Willkommen bei TechStore   Bitte wählen Sie Ihre Sprache',
    logingoogle:'Mit Google anmelden',
    loginmsg:'anmelden um fortzufahren',
    loginundermsg:'zugang zu exklusiven produkten',
    exclusive:'EXKLUSIV',
    discount:'RABATT',  
    securitymsg:'Ihre Daten und Transaktionen sind immer verschlüsselt und sicher.',
    paymentmsg:'Wir akzeptieren alle wichtigen Kreditkarten und PayPal.',
    supportmsg:'Unser Support-Team ist hier, um Ihnen 24/7 zu helfen.',
    deliverymsg:'Wir bieten schnelle und zuverlässige Lieferungsdienste.',
    securityTitle:'Sicher',
    paymentTitle:'Zahlungsmethode',
    supportTitle:'Support',
    deliveryTitle:'Lieferung',
  },
  fr: {
    home: 'Accueil',
    products: 'Produits',
    settings: 'Paramètres',
    account: 'Mon Compte',
    darkMode: 'Mode Sombre',
    notifications: 'Notifications',
    language: 'Langue',
    viewAll: 'Voir Tout',
    cart: 'Panier',
    searchPlaceholder: 'Rechercher des produits...',
    all: 'Toutes les catégories',
    electronics: 'Électronique',
    clothing: 'Vêtements',
    books: 'Livres',
    accessories: 'Accessoires',
    aboutUs: 'À propos de nous',
    contact: 'Contact',
    privacyPolicy: 'Politique de confidentialité',
    termsOfService: 'Conditions d\'utilisation',
    quickLinks: 'Liens rapides',
    contactUs: 'Contactez-nous',
    followUs: 'Suivez-nous',
    allRightsReserved: 'Tous droits réservés',
    privacy: 'Confidentialité',
    terms: 'Conditions',
    sitemap: 'Plan du site',
    storeDescription: 'Votre guichet unique pour tout ce qui concerne la technologie. Des produits de qualité, des prix compétitifs et un excellent service.',
    myOrders: 'Mes Commandes',
    wishlist: 'Liste de Souhaits',
    paymentMethods: 'Moyens de Paiement',
    addresses: 'Adresses',
    logout: 'Déconnexion',
    email: 'E-mail',
    welcomeToStore: 'Bienvenue sur TechStore',
    discoverTech: 'Découvrez les dernières technologies et gadgets',
    shopNow: 'Acheter maintenant',
    featuredProducts: 'Produits vedettes',
    viewAllProducts: 'Voir tous les produits',
    ourProducts: 'Nos produits',
    viewAll: 'Voir tout',
    view: 'Voir',
    addToCart: 'Ajouter au panier',
    backToProducts: 'Retour aux produits',
    productNotFound: 'Produit non trouvé',
    shoppingCart: 'Panier',
    yourCartIsEmpty: 'Votre panier est vide',
    continueShopping: 'Continuer les achats',
    total: 'Total',
    selectCategory: 'Sélectionner une catégorie',
    allCategories: 'Toutes les catégories',
    audio: 'Audio',
    wearables: 'Appareils portables',
    cameras: 'Caméras',
    gaming: 'Jeux',
    search: 'Rechercher',
    nocmt: 'Aucun commentaire encore - soyez le premier à partager vos idées!',
    commentSectionTitle: 'Commentaires',
    commentButton:'ajouter un commentaire',
    step1:'Bienvenue! C\'est le header où vous pouvez naviguer.',
    step2:'Voici les cartes de produit. Cliquez sur l\'un d\'eux pour voir les détails.',
    step3:'Ce bouton vous mène à votre panier.',
    step4:'? voulez-vous activer le mode sombre ',
    skiper:'passer',
    langBox:'Bienvenue sur TechStore   Veuillez sélectionner votre langue',
    logingoogle:'Se connecter avec Google',
    loginmsg:'se connecter pour continuer',
    loginundermsg:'acces des produits exclusifs',
    exclusive:'EXCLUSIF',
    discount:'RABA',
    securityTitle:'Sécurisé',
    securitymsg:'Vos données et transactions sont toujours cryptées et sécurisées.',
    paymentTitle:'Méthode de paiement',
    paymentmsg:'Nous acceptons toutes les principales cartes de crédit et PayPal.',
    supportTitle:'Support',
    supportmsg:'Notre équipe de support est ici pour vous aider 24/7.',
    deliveryTitle:'Livraison',
    deliverymsg:'Nous offrons des services de livraison rapides et fiables.',
  },
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
};

export const SettingsProvider = ({ children }) => {
  // Initialize state from localStorage or defaults
  const [darkMode, setDarkMode] = useState(() => {
    const saved = localStorage.getItem('darkMode');
    return saved ? JSON.parse(saved) : false;
  });

  const [notifications, setNotifications] = useState(() => {
    const saved = localStorage.getItem('notifications');
    return saved ? JSON.parse(saved) : true;
  });

  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'ar';
  });

  // Update localStorage when settings change
  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(darkMode));
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  useEffect(() => {
    localStorage.setItem('notifications', JSON.stringify(notifications));
  }, [notifications]);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const toggleDarkMode = () => setDarkMode(prev => !prev);
  const toggleNotifications = () => setNotifications(prev => !prev);
  const changeLanguage = (newLang) => setLanguage(newLang);
  
  // Helper function to get translations
  const t = (key) => translations[language]?.[key] || translations.en[key];

  const value = {
    darkMode,
    toggleDarkMode,
    notifications,
    toggleNotifications,
    language,
    changeLanguage,
    t, // Add translation helper
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}; 